name: Update Exchange Rate
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install
        run: pip install requests pandas pytz
      - name: Run
        run: python update_rate.py
      - name: Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add rate.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update rate" && git push)
